version: '3'

services:
  simple-golang-webdriver-test:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SAUCE_REGION=${SAUCE_REGION}
      - SAUCE_USERNAME=${SAUCE_USERNAME}
      - SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY}
    container_name: golang_webdriver
